spring:
  application:
    name: admin-server
  zipkin:
    base-url: http://localhost:9411
#  boot:
#    admin:
#      client:
#        url: http://localhost:7007
server:
  port: 7007
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: ["health","info"]
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:7000/eureka/,http://${eureka.instance.hostname}:7001/eureka/
