server:
  port: 7004
spring:
  application:
    name: consumer-server-ribbon
  zipkin:
    base-url: http://localhost:9411
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:7000/eureka/,http://${eureka.instance.hostname}:7001/eureka/
