server:
  port: 7002
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      #Eureka注册中心地址 多个逗号隔开
      defaultZone: http://${eureka.instance.hostname}:7000/eureka/,http://${eureka.instance.hostname}:7001/eureka/
spring:
  application:
    #请求通过服务名来调用 一定要写
    name: data-server
    #链路追踪监控地址
  zipkin:
    base-url: http://localhost:9411
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://hz.0ooo0.cn/school
#  boot:
#    admin:
#      client:
#        url: http://localhost:7007

