spring:
  application:
    name: zipkin-server
#  boot:
#    admin:
#      client:
#        url: http://localhost:7007

server:
  port: 9411
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:7000/eureka/,http://${eureka.instance.hostname}:7001/eureka/
management:
  metrics:
    web:
      server:
        auto-time-requests: false
