server:
  port: 7006
spring:
  application:
    name: zuul-server
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:7007
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:7000/eureka/,http://${eureka.instance.hostname}:7001/eureka/
zuul:
  routes:
#   配置路由 名字随便起 两个属性 path: serviceId serviceId是Eureka中要访问的服务名
    api-feign:
      path: /api/feign/**
      serviceId: CONSUMER-SERVER-FEIGN
    api-ribbon:
      path: /api/ribbon/**
      serviceId: CONSUMER-SERVER-RIBBON
